//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketMatch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatchDetail()
        {
            this.PlayerDetails = new HashSet<PlayerDetail>();
        }
    
        public int MatchId { get; set; }
        public string MatchName { get; set; }
        public System.DateTime MatchDate { get; set; }
        public string TeamOne { get; set; }
        public string TeamTwo { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerDetail> PlayerDetails { get; set; }
    }
}
