//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketMatch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerDetail
    {
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Position { get; set; }
        public string Team { get; set; }
        public int MatchId { get; set; }
    
        public virtual MatchDetail MatchDetail { get; set; }
    }
}
